name: Update Calendar

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pillow requests

      - name: Run python main.py
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
        run: python main.py

      - name: Commit and Push Calendar Image
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add out.png
          git commit -m "Update calendar image" || exit 0
          git push
